import { Container } from "@/shared/components/shared";
import { Suspense } from "react";

export const metadata = {
  title: "Админ-панель",
  description: "Generated by Next.js",
};

export default function AdminLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main className="min-h-screen">
      <Container>
        <Suspense>
        </Suspense>
        {children}
      </Container>
    </main>
  );
}
