import { Container, Header } from "@/shared/components/shared";

export const metadata = {
  title: "Смартфоны | Корзина",
  description: "Generated by Next.js",
};

export default function CartLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main className="min-h-screen bg-[#F4F1EE]">
      <Container>
        <Header className="border-b-gray-200" hasCart={false} />
        {children}
      </Container>
    </main>
  );
}
